name: Build and publish arm32v5 image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of cloudflared to build (e.g., 2025.10.1)'
        required: true
        type: string
      tag_latest:
        description: 'Also tag the image as “latest-arm32v5”?'
        required: false
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: your-org/cloudflared
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Environment Variables
        run: |
          echo "IMAGE_NAME=gamergambit/cloudflared_arm32v5" >> $GITHUB_ENV

      - name: Download upstream binary
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/download/${{ github.event.inputs.version }}/cloudflared-linux-arm

      - name: Publish Docker Image to Container Registry
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm/v5
          tags: |
              ghcr.io/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}-arm32v5
              ${{ github.event.inputs.tag_latest == 'true' && format('ghcr.io/{0}:latest-arm32v5', env.IMAGE_NAME) || null }}
          outputs: |
            type=image
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false

      - name: Save Docker Image as File
        run: docker save ghcr.io/${{ env.IMAGE_NAME }}:latest | gzip > dockerimage.tar.gz

      - name: Publish Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudflared-${{ github.event.inputs.version }}-arm32v5
          path: dockerimage.tar.gz